version: '3.5'

services:
  db:
    image: mariadb
    container_name: cloud_mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  app:
    image: nextcloud-config
    container_name: cloud_app
    restart: always
    volumes:
      - type: volume
        source: nextcloud
        target: /var/www/html
        volume:
          nocopy: false
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: cloud_nginx
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./log/nginx/:/var/log/nginx/:rw
    env_file:
      - nginx.env
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: cloud_proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf/proxy/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  omgwtfssl:
    image: paulczar/omgwtfssl
    container_name: cloud_omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    env_file:
      - ssl.env
    networks:
      - proxy-tier

volumes:
  db:
    name: nextcloud-db
  nextcloud:
    name: nextcloud-app
  certs:
    name: nextcloud-certs
  vhost.d:
    name: nextcloud-vhost
  html:
    name: nextcloud-html

networks:
  proxy-tier:
    name: nextcloud-proxy